sonar.organization=marcelomiyake
sonar.projectKey=marcelomiyake_hotel-ddd-cleanarch-cqrs
sonar.projectName=hotel-ddd-cleanarch-cqrs
sonar.sourceEncoding=UTF-8

sonar.sources=services/catalog-service/src/main/java,services/reservation-service/src/main/java,web/src
sonar.tests=services/catalog-service/src/test/java,services/reservation-service/src/test/java,web/test
sonar.test.inclusions=**/*Test.java,**/*Tests.java,**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx
sonar.java.binaries=services/catalog-service/target/classes,services/reservation-service/target/classes
sonar.java.test.binaries=services/catalog-service/target/test-classes,services/reservation-service/target/test-classes
sonar.coverage.jacoco.xmlReportPaths=services/catalog-service/target/site/jacoco/jacoco.xml,services/reservation-service/target/site/jacoco/jacoco.xml
sonar.javascript.lcov.reportPaths=web/coverage/lcov.info
sonar.coverage.exclusions=web/src/main.tsx
sonar.qualitygate.wait=true
